### ISSUE TITLE
error FS0039: The field, constructor or member 'UseStaticFiles' is not defined

### ISSUE THREAD

**Issue by AlfranKeith** [dustinmoris/Giraffe#122]
I seem to be having problems from the get go. After installation and creating a new project via dotnet new, it is unable to find the Giraffe.Razor package in nugget for version beta-200. 

>  error NU1102: Unable to find package Giraffe.Razor with version (>= 0.1.0-beta-200)\r

So I switch it over to beta-100 but run into the error above.

What am I doing wrong? Thanks!

**Comment by JonCanning** [comment]
Giraffe.Razor is on version 0.1.0-beta-100, so that's correct. You'll also need `Microsoft.AspNetCore.StaticFiles`

**Comment by AlfranKeith** [comment]
The latest template may have something wrong with it then if 200 is still not out as this is what I have:

>     <PackageReference Include="Giraffe" Version="0.1.0-beta-110" />
>     <PackageReference Include="Giraffe.Razor" Version="0.1.0-beta-200" />

I also appear to have static files
>     <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.*" />

Sorry, new to all this.

**Comment by JonCanning** [comment]
Check my example here

https://github.com/JonCanning/GiraffeIIS

**Comment by AlfranKeith** [comment]
Thanks! That sorted it out. I think Giraffe and Giraffe.Razor versions on the project template got switched around,

**Comment by dustinmoris** [comment]
Hi, yes this was a stupid bug introduced in the latest version. Has been fixed and will be released shortly now. Sorry for the confusion.

**Comment by SoulFireMage** [comment]
This problem still exists in the Giraffe template - I can't make the Giraffe.Razor stuff work at all right now. Any update to this?
